server:
  port: ${SERVER_PORT}
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    database-platform: ${JPA_DIALECT}
    hibernate:
      ddl-auto: ${DDL_AUTO}
    properties:
      javax:
        persistence:
          validation:
            mode: none
